In [1]:
import numpy as np
import os
import matplotlib.pyplot as plt
from typing import List
import json
from MyMLP.MyMLP import MyMLP


In [3]:
import cv2
import numpy as np
from MyMLP.MyMLP import MyMLP

dataset_path = '../data'
images, labels = MyMLP.load_images(dataset_path)

class_names = ['Barbe a Papa', 'Churros', 'Pomme damour']
class_to_index = {class_name: index for index, class_name in enumerate(class_names)}
num_classes = len(class_names)

# Convertir les labels en vecteurs one-hot 
one_hot_labels = []
for label in labels:
    one_hot = np.ones(num_classes)*-1 # Initialiser un vecteur de zéros
    one_hot[class_to_index[label]] = 1  # Placer un 1 à l'indice qui correspond au label
    one_hot_labels.append(one_hot)

one_hot_labels = np.array(one_hot_labels)
print(one_hot_labels)

desired_size = (25, 25)
resized_images = [cv2.resize(image, desired_size) for image in images]

train_images, train_labels, test_images, test_labels = MyMLP.split_dataset(resized_images, one_hot_labels, train_ratio=0.8)
train_images = [image.flatten() for image in train_images]
train_images = np.array(train_images)

print(train_images.shape)


[[ 1. -1. -1.]
 [ 1. -1. -1.]
 [ 1. -1. -1.]
 [ 1. -1. -1.]
 [ 1. -1. -1.]
 [ 1. -1. -1.]
 [ 1. -1. -1.]
 [ 1. -1. -1.]
 [ 1. -1. -1.]
 [ 1. -1. -1.]
 [ 1. -1. -1.]
 [ 1. -1. -1.]
 [ 1. -1. -1.]
 [ 1. -1. -1.]
 [ 1. -1. -1.]
 [ 1. -1. -1.]
 [ 1. -1. -1.]
 [ 1. -1. -1.]
 [ 1. -1. -1.]
 [ 1. -1. -1.]
 [ 1. -1. -1.]
 [ 1. -1. -1.]
 [ 1. -1. -1.]
 [ 1. -1. -1.]
 [ 1. -1. -1.]
 [ 1. -1. -1.]
 [ 1. -1. -1.]
 [ 1. -1. -1.]
 [ 1. -1. -1.]
 [ 1. -1. -1.]
 [ 1. -1. -1.]
 [ 1. -1. -1.]
 [ 1. -1. -1.]
 [ 1. -1. -1.]
 [ 1. -1. -1.]
 [ 1. -1. -1.]
 [ 1. -1. -1.]
 [ 1. -1. -1.]
 [ 1. -1. -1.]
 [ 1. -1. -1.]
 [ 1. -1. -1.]
 [ 1. -1. -1.]
 [ 1. -1. -1.]
 [ 1. -1. -1.]
 [ 1. -1. -1.]
 [ 1. -1. -1.]
 [ 1. -1. -1.]
 [ 1. -1. -1.]
 [ 1. -1. -1.]
 [ 1. -1. -1.]
 [ 1. -1. -1.]
 [ 1. -1. -1.]
 [ 1. -1. -1.]
 [ 1. -1. -1.]
 [ 1. -1. -1.]
 [ 1. -1. -1.]
 [ 1. -1. -1.]
 [ 1. -1. -1.]
 [ 1. -1. -1.]
 [ 1. -1. -1.]
 [ 1. -1. -1.]
 [ 1. -1. -1.]
 [ 1. -1. -1.]
 [ 1. -1. -1.]
 [ 1. -1. -1.]
 [ 1. -1. -1.]
 [ 1. -1. 

ValueError: setting an array element with a sequence. The requested array has an inhomogeneous shape after 1 dimensions. The detected shape was (253,) + inhomogeneous part.

In [4]:
print(train_images[0].shape)

(1875,)


In [5]:
print(len(labels))

317


In [6]:
mlp = MyMLP([1875, 100, 3])

In [ ]:
mlp.train(train_images, train_labels, is_classification=True, iteration_count=1000000, alpha=0.001)


In [ ]:
tab =(mlp.loss)
plt.plot(range(0, len(tab) * 1000, 1000), tab)  
plt.xlabel('Nombre d\'itérations')
plt.ylabel('Perte moyenne')
plt.title('Évolution de la perte au fil des itérations')
plt.show()